# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: 算法花园・笔记
site_url: https://note.xiang578.com/
site_description: Ryen personal note site
site_author: Ryen Xiang
repo_url: https://github.com/xiang578/xiang578.github.io
repo_name: xiang578
# edit_uri:
theme:
  name: material
  #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  features:
    - navigation.expand 
    - navigation.sections
    - tabs 
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - search
  - git-revision-date
  - roamlinks 
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

# Copyright
copyright: 'Copyright &copy; 2021 - 2021 Ryen Xiang'
google_analytics:
  - 'UA-65866729-2'
  - 'auto'
extra:
  disqus: "xiang578"
nav:
  - About:
    - Hi: index.md
    - Now: now.md
    - ChangeLog: ChangeLog.md
    - 2021 Reading: "2021 Reading.md"
  - Paper:
    - "how to read a paper.md"
  - Book:
    - 哲学家都干了些什么: "哲学家都干了些什么.md"
  - 哲学: 
    - 哲学: 哲学.md
  - 数字生活:
    - Git: git.md
    - VS Code: "VS Code.md"
    - 密码软件: "password.md"
  - Competitive Programming:
    - Competitive Programming: "CP/Competitive Programming.md"
    - LeetCode 检查清单: "CP/LeetCode CheckList.md"
    - 图论: "CP/图论.md"
    - LeetCode 题解:
      - 每日 1 题:
        - 20210625 852 山脉数组的峰顶索引: "CP/LeetCode/20210625 852 山脉数组的峰顶索引.md"
