# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: Ryenotes
repo_url: https://github.com/xiang578/xiang578.github.io
repo_name: xiang578
# edit_uri:
theme:
  name: material
  #  favicon: attachment/portrait.png
  language: zh # 中文，解决中文搜索问题
  features:
    - navigation.expand 
    - tabs 
markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
  - git-revision-date
  - search
  - roamlinks 
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

# Copyright
copyright: 'Copyright &copy; 2021 - 2021 Ryen Xiang'
google_analytics:
  - 'UA-65866729-2'
  - 'auto'
extra:
  disqus: "xiang578"
nav:
  - About:
    - Hi: 有关笔记.md
    - Now: now.md
  - 哲学: 
    - S: 哲学.md